import React from "react";
import { Section } from "../common";
import { useTranslation } from "react-i18next";

const About = () => {
  const { t } = useTranslation();
  return (
    <Section id="about">
      <h2>{t("About")}</h2>
      <p>
        JOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJJOWEFOJ
      </p>
    </Section>
  );
};

export default About;
